import { collection, addDoc } from "firebase/firestore";
import { db } from "./src/firebase.js";

const products = [
  {
    name: "iPhone 14 Pro Max",
    price: 1099,
    category: "Smartphones",
    featured: true,
    imageUrl: "https://example.com/iphone14promax.jpg",
    stock: 10,
    description: "Good product",
    rating: 4.7,
  },
  {
    name: "Samsung Galaxy S22",
    price: 899,
    category: "Smartphones",
    featured: true,
    imageUrl: "https://example.com/samsungs22.jpg",
    stock: 10,
    description: "Good product",
    rating: 4.7,
  },
  {
    name: "OnePlus 10 Pro",
    price: 799,
    category: "Smartphones",
    featured: false,
    imageUrl: "https://example.com/oneplus10pro.jpg",
    stock: 10,
    description: "Good product",
    rating: 4.7,
  },
  {
    name: "MacBook Pro 16-inch",
    price: 2399,
    category: "Laptops",
    featured: true,
    imageUrl: "https://example.com/macbookpro16.jpg",
    stock: 10,
    description: "Good product",
    rating: 4.7,
  },
  {
    name: "Dell XPS 13",
    price: 1199,
    category: "Laptops",
    featured: false,
    imageUrl: "https://example.com/dellxps13.jpg",
    stock: 10,
    description: "Good product",
    rating: 4.7,
  },
  {
    name: "Sony WH-1000XM4",
    price: 349,
    category: "Headphones",
    featured: true,
    imageUrl: "https://example.com/sonywh1000xm4.jpg",
    stock: 9,
    description: "Good product",
    rating: 4.7,
  },
  {
    name: "Bose QuietComfort 35 II",
    price: 299,
    category: "Headphones",
    featured: false,
    imageUrl: "https://example.com/boseqc35ii.jpg",
    stock: 130,
    description: "Good product",
    rating: 4.7,
  },
  {
    name: 'Samsung 65" QLED TV',
    price: 1799,
    category: "Televisions",
    featured: true,
    imageUrl: "https://example.com/samsungqled.jpg",
    stock: 120,
    description: "Good product",
    rating: 4.7,
  },
  {
    name: 'LG 55" OLED TV',
    price: 1499,
    category: "Televisions",
    featured: false,
    imageUrl: "https://example.com/lgoled55.jpg",
    stock: 101,
    description: "Good product",
    rating: 4.7,
  },
  {
    name: "Apple AirPods Pro",
    price: 249,
    category: "Accessories",
    featured: true,
    imageUrl: "https://example.com/airpodspro.jpg",
    stock: 1,
    description: "Good product",
    rating: 4.7,
  },
  {
    name: "Samsung Galaxy Watch 5",
    price: 399,
    category: "Wearables",
    featured: false,
    imageUrl: "https://example.com/galaxywatch5.jpg",
    stock: 7,
    description: "Good product",
    rating: 4.7,
  },
];

const categories = [
  {
    name: "Smartphones",
    icon: "https://example.com/smartphones-icon.png",
  },
  {
    name: "Laptops",
    icon: "https://example.com/laptops-icon.png",
  },
  {
    name: "Headphones",
    icon: "https://example.com/headphones-icon.png",
  },
  {
    name: "Televisions",
    icon: "https://example.com/televisions-icon.png",
  },
  {
    name: "Accessories",
    icon: "https://example.com/accessories-icon.png",
  },
  {
    name: "Wearables",
    icon: "https://example.com/wearables-icon.png",
  },
];

async function seedFirestore() {
  try {
    const productsCollection = collection(db, "products");
    const categoriesCollection = collection(db, "categories");

    for (const product of products) {
      // Document IDs will be autogenerated.
      await addDoc(productsCollection, product);
    }

    for (const category of categories) {
      await addDoc(categoriesCollection, category);
    }

    console.log("Firestore seeded successfully!");
  } catch (error) {
    console.error("Error seeding Firestore:", error);
  }
}

seedFirestore();
